version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Singapore
    open-pull-requests-limit: 10
    groups:
      external-repositories:
        patterns:
          - "@haneoka/vega"
          - "@haneoka/vega-*"
          - "@haneoka/altair"
          - "@haneoka/altair-*"
          - "@haneoka/deneb"
          - "@haneoka/deneb-*"
