export type CapabilityStatus = "available" | "planned" | "external";

export type CapabilityDomain = "home" | "catalog" | "tools" | "community" | "admin" | "rankings" | "games" | "profile";

export type CapabilityKind =
  "workspace" | "catalog" | "detail" | "tool" | "studio" | "runtime" | "account" | "external";

export type CapabilityAccessLevel = "public" | "browser-local" | "identity" | "verified-game" | "moderator";
export type CapabilityRegion = "global" | "jp" | "en" | "tw" | "cn" | "kr";
export type CapabilityNavigationTarget = "shell" | "domain" | "workspace";
export type CapabilityDataSource = "catalog" | "media" | "browser" | "worker" | "d1" | "r2-documents" | "external";
export type CapabilityOperation =
  | "read"
  | "search"
  | "filter"
  | "sort"
  | "play"
  | "preview"
  | "download"
  | "calculate"
  | "simulate"
  | "track"
  | "create"
  | "edit"
  | "revise"
  | "publish"
  | "comment"
  | "react"
  | "follow"
  | "import"
  | "export"
  | "sync"
  | "submit"
  | "manage"
  | "moderate";

export interface CapabilityRoutes {
  detail?: string | readonly string[];
  search?: string;
  create?: string;
  edit?: string;
  revision?: string;
}

export interface CapabilityAccess {
  read: CapabilityAccessLevel;
  write?: CapabilityAccessLevel;
  participate?: CapabilityAccessLevel;
}

export interface CapabilityScale {
  cardinality: "bounded" | "catalog" | "stream";
  transport: "inline" | "sharded" | "cursor";
  render: "static" | "windowed" | "paged";
}

export interface CapabilityNavigation {
  order: number;
  targets: readonly CapabilityNavigationTarget[];
}

export interface Capability {
  id: string;
  domain: CapabilityDomain;
  label: string;
  route: string;
  routes?: CapabilityRoutes;
  status: CapabilityStatus;
  kind: CapabilityKind;
  access: CapabilityAccess;
  regions: readonly CapabilityRegion[];
  scale: CapabilityScale;
  operations: readonly CapabilityOperation[];
  data: readonly CapabilityDataSource[];
  navigation: CapabilityNavigation;
}

type CapabilityInput = Omit<Capability, "access" | "regions" | "scale" | "data"> &
  Partial<Pick<Capability, "access" | "regions" | "scale" | "data">>;

export const allGameRegions = ["jp", "en", "tw", "cn", "kr"] as const satisfies readonly CapabilityRegion[];

const scales = {
  bounded: { cardinality: "bounded", transport: "inline", render: "static" },
  catalog: { cardinality: "catalog", transport: "sharded", render: "windowed" },
  stream: { cardinality: "stream", transport: "cursor", render: "windowed" },
  paged: { cardinality: "catalog", transport: "cursor", render: "paged" },
} as const satisfies Record<string, CapabilityScale>;

const nav = (order: number, ...targets: CapabilityNavigationTarget[]): CapabilityNavigation => ({ order, targets });

const defineCapability = (input: CapabilityInput): Capability => ({
  access: { read: "public" },
  regions: allGameRegions,
  scale: scales.catalog,
  data: ["catalog", "media"],
  ...input,
});

export const capabilities = [
  defineCapability({
    id: "home",
    domain: "home",
    label: "Home",
    route: "/",
    status: "available",
    kind: "workspace",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read"],
    data: ["catalog", "browser"],
    navigation: nav(0, "shell"),
  }),
  defineCapability({
    id: "home-overview",
    domain: "home",
    label: "Overview",
    route: "/#overview",
    status: "available",
    kind: "workspace",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read"],
    data: ["catalog", "browser"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "home-schedule",
    domain: "home",
    label: "Schedule",
    route: "/#schedule",
    status: "available",
    kind: "catalog",
    regions: ["global"],
    operations: ["read"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "home-birthdays",
    domain: "home",
    label: "Birthdays",
    route: "/#birthdays",
    status: "available",
    kind: "catalog",
    regions: ["global"],
    operations: ["read"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "home-community",
    domain: "home",
    label: "Community",
    route: "/#community",
    status: "available",
    kind: "catalog",
    regions: ["global"],
    operations: ["read"],
    data: ["worker", "d1"],
    navigation: nav(50, "domain", "workspace"),
  }),
  defineCapability({
    id: "home-updates",
    domain: "home",
    label: "Archive updates",
    route: "/#updates",
    status: "available",
    kind: "catalog",
    regions: ["global"],
    operations: ["read"],
    navigation: nav(60, "domain", "workspace"),
  }),

  defineCapability({
    id: "catalog",
    domain: "catalog",
    label: "Catalog",
    route: "/catalog",
    status: "available",
    kind: "workspace",
    scale: scales.bounded,
    operations: ["read"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "songs",
    domain: "catalog",
    label: "Songs",
    route: "/catalog/songs",
    routes: { detail: "/catalog/songs?song=:id", search: "/catalog/songs?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter", "sort", "play"],
    navigation: nav(10, "shell", "domain", "workspace"),
  }),
  defineCapability({
    id: "member-cards",
    domain: "catalog",
    label: "Members",
    route: "/catalog/member-cards",
    routes: { detail: "/catalog/member-cards?card=:id", search: "/catalog/member-cards?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter", "sort"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "support-cards",
    domain: "catalog",
    label: "Snaps",
    route: "/catalog/support-cards",
    routes: { detail: "/catalog/support-cards?snap=:id", search: "/catalog/support-cards?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter", "sort"],
    navigation: nav(30, "domain", "workspace"),
  }),
  defineCapability({
    id: "characters",
    domain: "catalog",
    label: "Characters",
    route: "/catalog/characters",
    routes: { detail: "/catalog/characters?character=:id", search: "/catalog/characters?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter"],
    navigation: nav(90, "domain", "workspace"),
  }),
  defineCapability({
    id: "stories",
    domain: "catalog",
    label: "Stories",
    route: "/catalog/stories",
    routes: { search: "/catalog/stories/afterlive?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter", "sort", "play", "preview"],
    navigation: nav(60, "domain", "workspace"),
  }),
  defineCapability({
    id: "comics",
    domain: "catalog",
    label: "Comics",
    route: "/catalog/comics",
    routes: { search: "/catalog/comics?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter"],
    navigation: nav(50, "domain", "workspace"),
  }),
  defineCapability({
    id: "stamps",
    domain: "catalog",
    label: "Stamps",
    route: "/catalog/stamps",
    routes: { search: "/catalog/stamps?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "live2d",
    domain: "catalog",
    label: "Live2D",
    route: "/catalog/live2d",
    routes: {},
    status: "available",
    kind: "runtime",
    operations: ["read", "preview", "import", "export"],
    data: ["catalog", "media", "browser"],
    navigation: nav(110, "domain", "workspace"),
  }),
  defineCapability({
    id: "asset-explorer",
    domain: "catalog",
    label: "Assets",
    route: "/catalog/assets",
    routes: { detail: "/catalog/assets/:path(.*)", search: "/catalog/assets?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "preview", "download"],
    data: ["catalog", "media"],
    navigation: nav(120, "domain", "workspace"),
  }),
  defineCapability({
    id: "items",
    domain: "catalog",
    label: "Items",
    route: "/catalog/items",
    routes: { detail: "/catalog/items?item=:id", search: "/catalog/items?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search", "filter"],
    navigation: nav(70, "domain", "workspace"),
  }),
  defineCapability({
    id: "band-items",
    domain: "catalog",
    label: "Band Items",
    route: "/catalog/band-items",
    routes: { detail: "/catalog/band-items?band=:band&item=:id" },
    status: "available",
    kind: "catalog",
    operations: ["read", "filter"],
    navigation: nav(80, "domain", "workspace"),
  }),
  defineCapability({
    id: "help",
    domain: "catalog",
    label: "Help",
    route: "/catalog/help",
    routes: { search: "/catalog/help?q=:query" },
    status: "available",
    kind: "catalog",
    operations: ["read", "search"],
    navigation: nav(240, "domain", "workspace"),
  }),
  defineCapability({
    id: "events",
    domain: "catalog",
    label: "Events",
    route: "/catalog/events",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(270, "domain", "workspace"),
  }),
  defineCapability({
    id: "gacha",
    domain: "catalog",
    label: "Gacha",
    route: "/catalog/gacha",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(280, "domain", "workspace"),
  }),
  defineCapability({
    id: "login-campaigns",
    domain: "catalog",
    label: "Login Bonuses",
    route: "/catalog/login-campaigns",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(290, "domain", "workspace"),
  }),
  defineCapability({
    id: "shop",
    domain: "catalog",
    label: "Shop",
    route: "/catalog/shop",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(300, "domain", "workspace"),
  }),
  defineCapability({
    id: "exchange",
    domain: "catalog",
    label: "Exchange",
    route: "/catalog/exchange",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(310, "domain", "workspace"),
  }),
  defineCapability({
    id: "circle",
    domain: "catalog",
    label: "Circle",
    route: "/catalog/circle",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(320, "domain", "workspace"),
  }),
  defineCapability({
    id: "challenge",
    domain: "catalog",
    label: "Challenge Live",
    route: "/catalog/challenge",
    status: "available",
    kind: "catalog",
    operations: ["read"],
    navigation: nav(330, "domain", "workspace"),
  }),

  defineCapability({
    id: "tools",
    domain: "tools",
    label: "Tools",
    route: "/tools",
    status: "available",
    kind: "workspace",
    access: { read: "browser-local", write: "browser-local" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read"],
    data: ["browser"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "chart-editor",
    domain: "tools",
    label: "Chart Editor",
    route: "/tools/chart-editor",
    status: "available",
    kind: "studio",
    access: { read: "browser-local", write: "browser-local" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "create", "edit", "play", "preview", "import", "export"],
    data: ["browser", "media"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "story-editor",
    domain: "tools",
    label: "Story Editor",
    route: "/tools/story-editor",
    status: "available",
    kind: "studio",
    access: { read: "browser-local", write: "browser-local" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "create", "edit", "play", "preview", "import", "export"],
    data: ["browser", "catalog", "media"],
    navigation: nav(20, "domain", "workspace"),
  }),

  defineCapability({
    id: "community",
    domain: "community",
    label: "Community",
    route: "/community",
    status: "available",
    kind: "workspace",
    regions: ["global"],
    scale: scales.stream,
    operations: ["read", "search", "filter", "sort", "create", "edit", "revise", "comment", "react", "follow"],
    data: ["worker", "d1"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "community-posts",
    domain: "community",
    label: "Feed",
    route: "/community/feeds",
    routes: {
      detail: "/community/posts/:id",
      search: "/community/feeds?q=:query",
      create: "/community/posts/new",
      edit: "/community/posts/:id/edit",
      revision: "/community/posts/:id/revisions/:revisionId",
    },
    status: "available",
    kind: "studio",
    access: { read: "public", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: [
      "read",
      "search",
      "filter",
      "sort",
      "create",
      "edit",
      "revise",
      "publish",
      "comment",
      "react",
      "manage",
    ],
    data: ["worker", "d1"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-mine",
    domain: "community",
    label: "Mine",
    route: "/community/mine",
    status: "available",
    kind: "catalog",
    access: { read: "identity", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: ["read", "filter", "sort", "edit", "revise", "manage"],
    data: ["worker", "d1"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-bookmarks",
    domain: "community",
    label: "Bookmarks",
    route: "/community/bookmarks",
    status: "available",
    kind: "catalog",
    access: { read: "identity", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: ["read", "filter", "manage"],
    data: ["worker", "d1"],
    navigation: nav(30, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-notifications",
    domain: "community",
    label: "Notifications",
    route: "/community/notifications",
    status: "available",
    kind: "catalog",
    access: { read: "identity", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: ["read", "manage"],
    data: ["worker", "d1"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-activity",
    domain: "community",
    label: "My comments",
    route: "/community/activity",
    status: "available",
    kind: "catalog",
    access: { read: "identity", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: ["read", "edit", "revise", "manage", "submit"],
    data: ["worker", "d1"],
    navigation: nav(45, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-tags",
    domain: "community",
    label: "Tags",
    route: "/community/tags",
    routes: { search: "/community/tags?q=:query" },
    status: "available",
    kind: "catalog",
    access: { read: "public", write: "identity" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "search", "filter", "follow", "manage"],
    data: ["worker", "d1"],
    navigation: nav(50, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-songs",
    domain: "community",
    label: "Bestdori Songs",
    route: "/community/songs-bestdori",
    status: "available",
    kind: "catalog",
    access: { read: "public" },
    regions: ["global"],
    scale: scales.catalog,
    operations: ["read", "search", "filter", "sort", "play", "preview"],
    data: ["worker", "external"],
    navigation: nav(55, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-playlists",
    domain: "community",
    label: "Playlists",
    route: "/community/playlists",
    routes: { detail: "/community/playlists/:id", search: "/community/playlists?q=:query" },
    status: "available",
    kind: "catalog",
    access: { read: "public" },
    regions: ["jp"],
    scale: scales.catalog,
    operations: ["read", "search", "filter", "play"],
    data: ["catalog", "browser", "external"],
    navigation: nav(54, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-stories",
    domain: "community",
    label: "Bestdori Stories",
    route: "/community/stories-bestdori",
    routes: { search: "/community/stories-bestdori/band?q=:query" },
    status: "available",
    kind: "catalog",
    access: { read: "public" },
    regions: ["global"],
    scale: scales.catalog,
    operations: ["read", "search", "filter", "sort", "play"],
    data: ["worker", "external"],
    navigation: nav(56, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-charts",
    domain: "community",
    label: "Charts",
    route: "/community/charts",
    routes: {
      detail: "/community/charts/:id",
      search: "/community/charts?q=:query",
      create: "/community/charts/new",
      edit: "/community/charts/:id/edit",
      revision: "/community/charts/:id/revisions/:revisionId",
    },
    status: "planned",
    kind: "studio",
    access: { read: "public", write: "identity" },
    regions: ["global"],
    scale: scales.stream,
    operations: [
      "read",
      "search",
      "filter",
      "sort",
      "play",
      "create",
      "edit",
      "revise",
      "publish",
      "comment",
      "react",
      "export",
    ],
    data: ["worker", "d1", "r2-documents", "media"],
    navigation: nav(50, "domain", "workspace"),
  }),
  defineCapability({
    id: "community-users",
    domain: "community",
    label: "Users",
    route: "/community/users",
    routes: { detail: "/community/users/:id", search: "/community/users?q=:query" },
    status: "planned",
    kind: "catalog",
    access: { read: "public", write: "identity" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "search", "filter", "follow"],
    data: ["worker", "d1"],
    navigation: nav(70, "domain", "workspace"),
  }),

  defineCapability({
    id: "admin",
    domain: "admin",
    label: "Admin",
    route: "/admin",
    status: "available",
    kind: "workspace",
    access: { read: "moderator", write: "moderator" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "manage", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(0, "domain"),
  }),
  defineCapability({
    id: "admin-overview",
    domain: "admin",
    label: "Overview",
    route: "/admin",
    status: "available",
    kind: "tool",
    access: { read: "moderator" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "admin-users",
    domain: "admin",
    label: "Users",
    route: "/admin/users",
    status: "available",
    kind: "account",
    access: { read: "moderator", write: "moderator" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "search", "filter", "manage", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "admin-posts",
    domain: "admin",
    label: "Posts",
    route: "/admin/posts",
    status: "available",
    kind: "tool",
    access: { read: "moderator", write: "moderator" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "search", "filter", "manage", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(30, "domain", "workspace"),
  }),
  defineCapability({
    id: "admin-reports",
    domain: "admin",
    label: "Reports",
    route: "/admin/reports",
    status: "available",
    kind: "tool",
    access: { read: "moderator", write: "moderator" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "filter", "manage", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "admin-appeals",
    domain: "admin",
    label: "Appeals",
    route: "/admin/appeals",
    status: "available",
    kind: "tool",
    access: { read: "moderator", write: "moderator" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "filter", "manage", "moderate"],
    data: ["worker", "d1"],
    navigation: nav(50, "domain", "workspace"),
  }),
  defineCapability({
    id: "admin-operations",
    domain: "admin",
    label: "Operations",
    route: "/admin/operations",
    status: "available",
    kind: "tool",
    access: { read: "moderator" },
    regions: ["global"],
    scale: scales.paged,
    operations: ["read", "filter"],
    data: ["worker", "d1"],
    navigation: nav(60, "domain", "workspace"),
  }),

  defineCapability({
    id: "rankings",
    domain: "rankings",
    label: "Rankings",
    route: "/rankings",
    status: "planned",
    kind: "workspace",
    scale: scales.paged,
    operations: ["read", "filter", "sort"],
    data: ["worker", "d1"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "event-rankings",
    domain: "rankings",
    label: "Events",
    route: "/rankings/events",
    routes: { detail: "/rankings/events/:eventId/:tier", search: "/rankings/events?q=:query" },
    status: "planned",
    kind: "tool",
    scale: scales.paged,
    operations: ["read", "search", "filter", "sort", "track"],
    data: ["worker", "d1"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "song-rankings",
    domain: "rankings",
    label: "Songs",
    route: "/rankings/songs",
    routes: { detail: "/rankings/songs/:songId/:difficulty", search: "/rankings/songs?q=:query" },
    status: "planned",
    kind: "tool",
    scale: scales.paged,
    operations: ["read", "search", "filter", "sort"],
    data: ["worker", "d1"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "player-rankings",
    domain: "rankings",
    label: "Players",
    route: "/rankings/players",
    routes: { detail: "/rankings/players/:region/:playerId", search: "/rankings/players?q=:query" },
    status: "planned",
    kind: "tool",
    scale: scales.paged,
    operations: ["read", "search", "filter", "sort"],
    data: ["worker", "d1"],
    navigation: nav(30, "domain", "workspace"),
  }),
  defineCapability({
    id: "goal-master",
    domain: "rankings",
    label: "Goal Master",
    route: "/rankings/goal-master",
    routes: { detail: "/rankings/goal-master/:id", search: "/rankings/goal-master?q=:query" },
    status: "planned",
    kind: "tool",
    scale: scales.paged,
    operations: ["read", "search", "filter", "sort"],
    data: ["worker", "d1"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "participate",
    domain: "rankings",
    label: "Participate",
    route: "/rankings/participate",
    status: "planned",
    kind: "account",
    access: { read: "identity", write: "verified-game", participate: "verified-game" },
    regions: allGameRegions,
    scale: scales.bounded,
    operations: ["read", "submit", "manage"],
    data: ["worker", "d1"],
    navigation: nav(50, "domain", "workspace"),
  }),

  defineCapability({
    id: "games",
    domain: "games",
    label: "Games",
    route: "/games",
    status: "planned",
    kind: "workspace",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read"],
    data: ["catalog", "browser"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "find-me",
    domain: "games",
    label: "Find Me",
    route: "/games/find-me",
    status: "planned",
    kind: "tool",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "play"],
    data: ["catalog", "browser"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "guess-who",
    domain: "games",
    label: "Guess Who",
    route: "/games/guess-who",
    status: "planned",
    kind: "tool",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "play"],
    data: ["catalog", "browser"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "chart-master",
    domain: "games",
    label: "Chart Master",
    route: "/games/chart-master",
    status: "planned",
    kind: "tool",
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "play", "simulate"],
    data: ["catalog", "media", "browser"],
    navigation: nav(30, "domain", "workspace"),
  }),

  defineCapability({
    id: "profile",
    domain: "profile",
    label: "Profile",
    route: "/profile",
    status: "planned",
    kind: "workspace",
    access: { read: "browser-local", write: "browser-local" },
    regions: allGameRegions,
    scale: scales.bounded,
    operations: ["read", "manage", "sync", "import", "export"],
    data: ["browser"],
    navigation: nav(0, "shell", "domain"),
  }),
  defineCapability({
    id: "profiles",
    domain: "profile",
    label: "Manager",
    route: "/profile/manager",
    routes: {
      detail: "/profile/manager/:profileId",
      create: "/profile/manager/new",
      edit: "/profile/manager/:profileId/edit",
    },
    status: "planned",
    kind: "account",
    access: { read: "browser-local", write: "browser-local" },
    scale: scales.bounded,
    operations: ["read", "create", "edit", "manage", "sync", "import", "export"],
    data: ["browser"],
    navigation: nav(10, "domain", "workspace"),
  }),
  defineCapability({
    id: "owned-cards",
    domain: "profile",
    label: "Cards",
    route: "/profile/cards",
    routes: { search: "/profile/cards?q=:query", edit: "/profile/cards/edit" },
    status: "planned",
    kind: "account",
    access: { read: "browser-local", write: "browser-local" },
    scale: scales.catalog,
    operations: ["read", "search", "filter", "sort", "edit", "import", "export", "sync"],
    data: ["catalog", "browser"],
    navigation: nav(20, "domain", "workspace"),
  }),
  defineCapability({
    id: "owned-items",
    domain: "profile",
    label: "Items",
    route: "/profile/items",
    routes: { search: "/profile/items?q=:query", edit: "/profile/items/edit" },
    status: "planned",
    kind: "account",
    access: { read: "browser-local", write: "browser-local" },
    scale: scales.catalog,
    operations: ["read", "search", "filter", "sort", "edit", "import", "export", "sync"],
    data: ["catalog", "browser"],
    navigation: nav(30, "domain", "workspace"),
  }),
  defineCapability({
    id: "profile-recognition",
    domain: "profile",
    label: "Recognition",
    route: "/profile/recognition",
    status: "planned",
    kind: "tool",
    access: { read: "browser-local", write: "browser-local" },
    scale: scales.bounded,
    operations: ["read", "import", "edit"],
    data: ["catalog", "browser"],
    navigation: nav(40, "domain", "workspace"),
  }),
  defineCapability({
    id: "preferences",
    domain: "profile",
    label: "Preferences",
    route: "/profile/preferences",
    routes: { edit: "/profile/preferences" },
    status: "planned",
    kind: "account",
    access: { read: "browser-local", write: "browser-local" },
    regions: ["global"],
    scale: scales.bounded,
    operations: ["read", "edit", "sync", "import", "export"],
    data: ["browser"],
    navigation: nav(50, "domain", "workspace"),
  }),
] as const satisfies readonly Capability[];

const inNavigationTarget = (capability: Capability, target: CapabilityNavigationTarget) =>
  capability.navigation.targets.includes(target);

export const availableCapabilities = capabilities.filter((capability) => capability.status === "available");

export const capabilityById = (id: string) => capabilities.find((capability) => capability.id === id);

export const capabilitiesIn = (
  domain: CapabilityDomain,
  status: CapabilityStatus = "available",
  target: CapabilityNavigationTarget = "domain",
) =>
  capabilities
    .filter(
      (capability) =>
        capability.domain === domain && capability.status === status && inNavigationTarget(capability, target),
    )
    .sort((a, b) => a.navigation.order - b.navigation.order);

export const workspaceCapabilitiesIn = (domain: CapabilityDomain, status: CapabilityStatus = "available") =>
  capabilitiesIn(domain, status, "workspace");
