import type { ArchiveMessageKey } from "~/i18n/messages";

type Translate = (key: ArchiveMessageKey) => string;

const valueMessageKeys = {
  accepted: "adminPage.values.accepted",
  active: "adminPage.values.active",
  allow: "adminPage.values.allow",
  archived: "adminPage.values.archived",
  attachment: "adminPage.values.attachment",
  block: "adminPage.values.block",
  cancelled: "adminPage.values.cancelled",
  comment: "adminPage.values.comment",
  copyright: "adminPage.values.copyright",
  create: "adminPage.values.create",
  deleted: "adminPage.values.deleted",
  dismissed: "adminPage.values.dismissed",
  draft: "adminPage.values.draft",
  edit: "adminPage.values.edit",
  expired: "adminPage.values.expired",
  failed: "adminPage.values.failed",
  harassment: "adminPage.values.harassment",
  hate: "adminPage.values.hate",
  hidden: "adminPage.values.hidden",
  locked: "adminPage.values.locked",
  migration_snapshot: "adminPage.values.migrationSnapshot",
  misinformation: "adminPage.values.misinformation",
  other: "adminPage.values.other",
  pending: "adminPage.values.pending",
  pinned: "adminPage.values.pinned",
  post: "adminPage.values.post",
  processing: "adminPage.values.processing",
  privacy: "adminPage.values.privacy",
  private: "adminPage.values.private",
  "profile-name": "adminPage.values.profileName",
  protected: "adminPage.values.protected",
  public: "adminPage.values.public",
  published: "adminPage.values.published",
  ready: "adminPage.values.ready",
  rejected: "adminPage.values.rejected",
  reserved: "adminPage.values.reserved",
  resolved: "adminPage.values.resolved",
  restore_snapshot: "adminPage.values.restoreSnapshot",
  restored: "adminPage.values.restored",
  review: "adminPage.values.review",
  reviewing: "adminPage.values.reviewing",
  running: "adminPage.values.running",
  scanning: "adminPage.values.scanning",
  sexual: "adminPage.values.sexual",
  spam: "adminPage.values.spam",
  succeeded: "adminPage.values.succeeded",
  superseded: "adminPage.values.superseded",
  suspended: "adminPage.values.suspended",
  uploaded: "adminPage.values.uploaded",
  uploading: "adminPage.values.uploading",
  unarchived: "adminPage.values.unarchived",
  unhidden: "adminPage.values.unhidden",
  unlocked: "adminPage.values.unlocked",
  unpinned: "adminPage.values.unpinned",
  user: "adminPage.values.user",
  verifying: "adminPage.values.verifying",
  violence: "adminPage.values.violence",
  global: "adminPage.resourceRegions.global",
  jp: "adminPage.resourceRegions.jp",
  kr: "adminPage.resourceRegions.kr",
  tw: "adminPage.resourceRegions.tw",
  cn: "adminPage.resourceRegions.cn",
  en: "adminPage.resourceRegions.en",
  "post.state.set": "adminPage.operations.actions.postStateSet",
  "comment.state.set": "adminPage.operations.actions.commentStateSet",
  "appeal.decision": "adminPage.operations.actions.appealDecision",
  "report.status.set": "adminPage.operations.actions.reportStatusSet",
  "user.role.set": "adminPage.operations.actions.userRoleSet",
  "user.restriction.create": "adminPage.operations.actions.userRestrictionCreate",
  "user.restriction.revoke": "adminPage.operations.actions.userRestrictionRevoke",
  "user.sessions.revoke": "adminPage.operations.actions.userSessionsRevoke",
  "resource.server.create": "adminPage.operations.actions.resourceServerCreate",
  "resource.server.update": "adminPage.operations.actions.resourceServerUpdate",
  "package.upload.create": "adminPage.operations.actions.packageUploadCreate",
  "package.upload.part": "adminPage.operations.actions.packageUploadPart",
  "package.upload.complete": "adminPage.operations.actions.packageUploadComplete",
  "package.upload.abort": "adminPage.operations.actions.packageUploadAbort",
  "resource.run.dispatch": "adminPage.operations.actions.resourceRunDispatch",
  appeal: "adminPage.operations.targets.appeal",
  report: "adminPage.operations.targets.report",
  restriction: "adminPage.operations.targets.restriction",
  resource_server: "adminPage.operations.targets.resourceServer",
  package_upload: "adminPage.operations.targets.packageUpload",
  package_part: "adminPage.operations.targets.packagePart",
  resource_run: "adminPage.operations.targets.resourceRun",
  member: "adminPage.roles.member",
  moderator: "adminPage.roles.moderator",
  admin: "adminPage.roles.admin",
  sign_in: "adminPage.restrictions.signIn",
  upload: "adminPage.restrictions.upload",
  write: "adminPage.restrictions.write",
} as const satisfies Record<string, ArchiveMessageKey>;

const reasonMessageKeys = {
  "system.entity_revision_superseded": "adminPage.values.superseded",
  "user.self_delete": "adminPage.values.deleted",
  "admin.dashboard.post.hide": "adminPage.history.hide",
  "admin.dashboard.post.unhide": "adminPage.history.unhide",
  "admin.dashboard.post.lock": "adminPage.history.lock",
  "admin.dashboard.post.unlock": "adminPage.history.unlock",
  "admin.dashboard.comment.hide": "adminPage.history.hide",
  "admin.dashboard.comment.unhide": "adminPage.history.unhide",
  "admin.dashboard.report.resolved": "adminPage.values.resolved",
  "admin.dashboard.report.dismissed": "adminPage.values.dismissed",
  "admin.dashboard.appeal.accepted": "adminPage.values.accepted",
  "admin.dashboard.appeal.rejected": "adminPage.values.rejected",
  "admin.dashboard.restrict.sign_in": "adminPage.restrictions.signIn",
  "admin.dashboard.restrict.upload": "adminPage.restrictions.upload",
  "admin.dashboard.restrict.write": "adminPage.restrictions.write",
  "admin.dashboard.restriction.revoke": "adminPage.actions.revokeRestriction",
} as const satisfies Record<string, ArchiveMessageKey>;

export const adminValueLabel = (value: string | null | undefined, t: Translate): string => {
  if (!value) return "—";
  const key = valueMessageKeys[value as keyof typeof valueMessageKeys];
  return key ? t(key) : value;
};

export const adminReasonLabel = (value: string | null | undefined, t: Translate): string => {
  if (!value) return "—";
  const key = reasonMessageKeys[value as keyof typeof reasonMessageKeys];
  return key ? t(key) : adminValueLabel(value, t);
};
