import type { ArchiveMessageKey } from "~/i18n/messages";
import type { CommunityBrowserFamily, CommunityOsFamily } from "~/types/community";

export const COMMUNITY_OS_LABEL_KEYS = {
  alpine_linux: "communityPage.device.os.alpine_linux",
  android: "communityPage.device.os.android",
  arch_linux: "communityPage.device.os.arch_linux",
  blackberry: "communityPage.device.os.blackberry",
  centos: "communityPage.device.os.centos",
  chromeos: "communityPage.device.os.chromeos",
  debian: "communityPage.device.os.debian",
  elementary: "communityPage.device.os.elementary",
  fedora: "communityPage.device.os.fedora",
  freebsd: "communityPage.device.os.freebsd",
  fuchsia: "communityPage.device.os.fuchsia",
  gentoo: "communityPage.device.os.gentoo",
  grapheneos: "communityPage.device.os.grapheneos",
  haiku: "communityPage.device.os.haiku",
  harmonyos: "communityPage.device.os.harmonyos",
  ios: "communityPage.device.os.ios",
  kaios: "communityPage.device.os.kaios",
  kali_linux: "communityPage.device.os.kali_linux",
  lineageos: "communityPage.device.os.lineageos",
  linux: "communityPage.device.os.linux",
  linux_mint: "communityPage.device.os.linux_mint",
  macos: "communityPage.device.os.macos",
  manjaro: "communityPage.device.os.manjaro",
  netbsd: "communityPage.device.os.netbsd",
  openbsd: "communityPage.device.os.openbsd",
  opensuse: "communityPage.device.os.opensuse",
  other: "communityPage.device.os.other",
  sailfish: "communityPage.device.os.sailfish",
  ubuntu: "communityPage.device.os.ubuntu",
  unknown: "communityPage.device.os.unknown",
  wear_os: "communityPage.device.os.wear_os",
  windows: "communityPage.device.os.windows",
} as const satisfies Record<CommunityOsFamily, ArchiveMessageKey>;

export const COMMUNITY_BROWSER_LABEL_KEYS = {
  arc: "communityPage.device.browserFamily.arc",
  bot: "communityPage.device.browserFamily.bot",
  brave: "communityPage.device.browserFamily.brave",
  chrome: "communityPage.device.browserFamily.chrome",
  chromium: "communityPage.device.browserFamily.chromium",
  duckduckgo: "communityPage.device.browserFamily.duckduckgo",
  edge: "communityPage.device.browserFamily.edge",
  electron: "communityPage.device.browserFamily.electron",
  firefox: "communityPage.device.browserFamily.firefox",
  floorp: "communityPage.device.browserFamily.floorp",
  helium: "communityPage.device.browserFamily.helium",
  internet_explorer: "communityPage.device.browserFamily.internet_explorer",
  librewolf: "communityPage.device.browserFamily.librewolf",
  opera: "communityPage.device.browserFamily.opera",
  opera_gx: "communityPage.device.browserFamily.opera_gx",
  other: "communityPage.device.browserFamily.other",
  safari: "communityPage.device.browserFamily.safari",
  samsung_internet: "communityPage.device.browserFamily.samsung_internet",
  tor: "communityPage.device.browserFamily.tor",
  unknown: "communityPage.device.browserFamily.unknown",
  vivaldi: "communityPage.device.browserFamily.vivaldi",
  webview: "communityPage.device.browserFamily.webview",
  yandex: "communityPage.device.browserFamily.yandex",
  zen: "communityPage.device.browserFamily.zen",
} as const satisfies Record<CommunityBrowserFamily, ArchiveMessageKey>;
