"""Deterministic fingerprints for code that can change build outputs."""

from __future__ import annotations

import os
from pathlib import Path

from core.config import ServerConfig
from core.contracts import PIPELINE_CONTRACT
from core.hashes import sha256_bytes, sha256_file
from core.manifests import stable_json


IGNORED_PARTS = {".venv", "__pycache__", "dist", "node_modules", "worker-assets"}
BUILD_INPUTS = (
    "scripts/build",
    "scripts/core",
    "scripts/extract",
    "scripts/requirements.txt",
    "scripts/verify/release.py",
    "packages/sonolus",
    "package.json",
    "pnpm-lock.yaml",
    "server/releaseWorkspace.ts",
)


def _files(root: Path) -> list[Path]:
    files: set[Path] = set()
    for relative in BUILD_INPUTS:
        candidate = root / relative
        if candidate.is_file():
            files.add(candidate)
            continue
        for current, directories, names in os.walk(candidate):
            directories[:] = sorted(value for value in directories if value not in IGNORED_PARTS)
            for name in sorted(names):
                file = Path(current) / name
                if file.suffix != ".pyc" and not any(part in IGNORED_PARTS for part in file.relative_to(root).parts):
                    files.add(file)
    return sorted(files)


def _output_configuration(config: ServerConfig) -> dict[str, object]:
    """Select only server settings that can change generated bytes or public URLs."""

    return {
        "server": config.id,
        "platform": config.platform,
        "unityVersion": config.unity_version,
        "criHcaKey": config.cri_hca_key,
        "masterCrypto": config.master_crypto,
    }


def build_fingerprint(project_root: Path, config: ServerConfig) -> str:
    files = _files(project_root)
    payload = "".join(f"{file.relative_to(project_root).as_posix()}:{sha256_file(file)}\n" for file in files)
    configuration = stable_json(_output_configuration(config))
    return sha256_bytes(f"{PIPELINE_CONTRACT}\n{configuration}{payload}")
