import type { AdvCommandName, CommandFieldDescriptor } from "@haneoka/story-editor";

const simplifiedCommandLabels: Record<AdvCommandName, string> = {
  In: "角色登场",
  Out: "角色退场",
  Talk: "普通对话",
  Delay: "延时",
  Shake: "角色震动",
  FadeOut: "淡出",
  FadeIn: "淡入",
  Focus: "镜头聚焦",
  Forward: "站位层级前移",
  Back: "站位层级后移",
  Flash: "闪白",
  Brightness: "亮度",
  MoveToRight: "角色右移",
  MoveToLeft: "角色左移",
  Bgm: "背景音乐",
  SoundVolume: "音量控制",
  Expression: "切换表情",
  Pause: "暂停动作",
  Resume: "继续动作",
  Location: "地点文字",
  Motion: "播放动作",
  Character: "切换立绘",
  Costume: "切换服装",
  Stage: "切换背景",
  Movie: "播放视频",
  Clip: "播放片段",
  Subtitles: "视频字幕",
  Wait: "等待输入",
  Still: "静态画面",
  Se: "效果声音",
  Angle: "角色角度",
  Pan: "镜头平移",
  Tilt: "镜头倾斜",
  TalkWindow: "对话框",
  ChatWindow: "聊天窗口",
  ChatTalk: "聊天消息",
  ChatStamp: "聊天贴图",
  ChatRead: "已读标记",
  ChoiceSet: "设置选项",
  ChoiceShow: "显示选项",
  GoTo: "跳转",
  PostEffect: "后处理",
  Frame: "画面框",
  Timeline: "时间轴",
  Look: "角色注视",
  Pedestal: "镜头升降",
  Track: "镜头跟踪",
  DoF: "景深",
  Role: "镜头滚转",
  CameraShake: "镜头震动",
  Voice: "角色语音",
  Zoom: "镜头缩放",
  Effect: "舞台特效",
  Alpha: "角色透明度",
  ForceAuto: "强制自动",
  StageEnv: "舞台环境",
  RimLight: "轮廓光",
  CancelDelay: "取消延时",
  MoveToUp: "角色上移",
  MoveToDown: "角色下移",
  MoveToForward: "角色前移",
  MoveToBack: "角色后移",
  MoveToDirection: "定向移动",
  ChatTyping: "输入中",
  LookTarget: "注视目标",
  PanV2: "场景平移",
  CommandGroup: "命令组",
};

const traditionalCommandLabels: Record<AdvCommandName, string> = {
  ...simplifiedCommandLabels,
  In: "角色登場",
  Out: "角色退場",
  Delay: "延時",
  FadeOut: "淡出",
  FadeIn: "淡入",
  Focus: "鏡頭聚焦",
  Forward: "站位層級前移",
  Back: "站位層級後移",
  Flash: "閃白",
  MoveToRight: "角色右移",
  MoveToLeft: "角色左移",
  SoundVolume: "音量控制",
  Expression: "切換表情",
  Pause: "暫停動作",
  Resume: "繼續動作",
  Location: "地點文字",
  Motion: "播放動作",
  Character: "切換立繪",
  Costume: "切換服裝",
  Stage: "切換背景",
  Movie: "播放影片",
  Clip: "播放片段",
  Subtitles: "影片字幕",
  Wait: "等待輸入",
  Still: "靜態畫面",
  Angle: "角色角度",
  Pan: "鏡頭平移",
  Tilt: "鏡頭傾斜",
  TalkWindow: "對話框",
  ChatWindow: "聊天視窗",
  ChatTalk: "聊天訊息",
  ChatStamp: "聊天貼圖",
  ChatRead: "已讀標記",
  ChoiceSet: "設定選項",
  ChoiceShow: "顯示選項",
  GoTo: "跳轉",
  PostEffect: "後處理",
  Frame: "畫面框",
  Look: "角色注視",
  Pedestal: "鏡頭升降",
  Track: "鏡頭跟蹤",
  DoF: "景深",
  Role: "鏡頭滾轉",
  CameraShake: "鏡頭震動",
  Voice: "角色語音",
  Zoom: "鏡頭縮放",
  Effect: "舞台特效",
  Alpha: "角色透明度",
  ForceAuto: "強制自動",
  StageEnv: "舞台環境",
  RimLight: "輪廓光",
  CancelDelay: "取消延時",
  MoveToUp: "角色上移",
  MoveToDown: "角色下移",
  MoveToForward: "角色前移",
  MoveToBack: "角色後移",
  MoveToDirection: "定向移動",
  ChatTyping: "輸入中",
  LookTarget: "注視目標",
  PanV2: "場景平移",
  CommandGroup: "命令群組",
};

const japaneseCommandLabels: Partial<Record<AdvCommandName, string>> = {
  Forward: "配置レイヤーを前へ",
  Back: "配置レイヤーを後ろへ",
  Subtitles: "動画字幕",
  Angle: "キャラクター角度",
  Role: "カメラロール",
  StageEnv: "ステージ環境",
};

const koreanCommandLabels: Partial<Record<AdvCommandName, string>> = {
  Forward: "배치 레이어 앞으로",
  Back: "배치 레이어 뒤로",
  Subtitles: "동영상 자막",
  Angle: "캐릭터 각도",
  Role: "카메라 롤",
  StageEnv: "스테이지 환경",
};

const simplifiedFieldLabels: Record<string, string> = {
  "ADV effect": "ADV 特效",
  Action: "操作",
  "Allow skip": "允许跳过",
  "Animation index": "动画序号",
  "Animation state": "动画状态",
  "Audio category": "音频分类",
  "Auto-stop after": "自动停止时间",
  Background: "背景资源",
  "Background blur": "背景模糊",
  "Background blur offset": "背景模糊偏移",
  "Battery level": "电量",
  "Blur intensity": "模糊强度",
  "Body angle": "身体角度",
  Brightness: "亮度",
  "Camera distance": "镜头距离",
  "Canvas layers": "画布图层",
  Character: "角色",
  "Character model": "角色模型",
  "Character (optional)": "角色（可选）",
  "Character voice": "角色语音",
  "Chat preset": "聊天预设",
  "Choice ID": "选项标识",
  "Choice text": "选项文本",
  Color: "颜色",
  "Continue immediately": "连续执行",
  "Conversation thread": "会话",
  "Costume index": "服装序号",
  "Crossfade duration": "过渡时长",
  "Depth offset": "纵深偏移",
  "Destination label": "目标标签",
  Dialogue: "对话内容",
  "Disable lip sync": "禁用口型同步",
  "Displayed sender": "显示发送者",
  "Displayed speaker name": "显示角色名",
  "Displayed title": "显示标题",
  Distance: "移动距离",
  Duration: "持续时间",
  Easing: "缓动",
  "Effect instance": "特效实例",
  "Environment component": "环境组件",
  Expression: "表情",
  "Face angle": "面部角度",
  "Fade duration": "淡化时长",
  "Fade in": "淡入时长",
  "Fade out": "淡出时长",
  "Focus slide rate": "焦点滑动比例",
  Frame: "画面框资源",
  "Frame instance": "画面框实例",
  "Horizontal gaze": "水平注视",
  "Horizontal offset": "水平偏移",
  "Horizontal rotation": "水平旋转",
  "Image opacity": "图像透明度",
  "Light color / state": "轮廓光颜色 / 状态",
  "Lip-sync character": "口型同步角色",
  "Lip-sync mode": "口型同步模式",
  "Live2D model": "Live2D 模型",
  Location: "地点",
  Message: "消息内容",
  Motion: "动作",
  "Mouth opening": "嘴型开合幅度",
  Music: "音乐资源",
  "Name display": "名称显示",
  Opacity: "透明度",
  "Opacity transition": "透明度过渡时长",
  "Overlay opacity": "遮罩透明度",
  "Overlay text": "横幅文字",
  Participants: "参与角色",
  "Playback delay": "播放延时",
  Position: "位置",
  "Post effect": "后处理资源",
  "Preset index": "预设序号",
  "Queued start delay": "排队播放延时",
  "Read count": "已读数量",
  "Read target chat preset": "已读目标",
  "Roll angle": "镜头滚转角度",
  "Scene label": "场景标签",
  "Screen mode": "屏幕模式",
  Sender: "发送者",
  "Sender chat preset": "发送者预设",
  "Shadow intensity": "阴影强度",
  "Sound effect": "音效资源",
  "Source character": "发起角色",
  "Stage position": "舞台站位",
  "Stamp asset": "贴图资源",
  "Start delay": "开始延时",
  "Start offset": "播放起点",
  Still: "静态画面资源",
  "Stop fade": "停止淡出时长",
  "Stop mode": "停止方式",
  Strength: "强度",
  Subtitle: "字幕",
  "Target character position": "目标角色站位",
  "Target volume": "目标音量",
  "Timeline asset": "时间轴资源",
  "Transition duration": "转场时长",
  "Transition mask": "转场遮罩",
  "Typing text": "输入状态文本",
  "Vertical gaze": "垂直注视",
  "Vertical offset": "垂直偏移",
  "Vertical rotation": "垂直旋转",
  Video: "视频资源",
  "Wait time": "等待时长",
  "Window style": "窗口样式",
  "World destination": "世界坐标目标",
  "World position": "世界坐标",
  "Zoom ratio": "缩放倍率",
};

const traditionalFieldLabels: Record<string, string> = {
  ...simplifiedFieldLabels,
  "Overlay text": "橫幅文字",
  "ADV effect": "ADV 特效",
  "Allow skip": "允許跳過",
  "Animation index": "動畫序號",
  "Animation state": "動畫狀態",
  "Audio category": "音訊分類",
  "Auto-stop after": "自動停止時間",
  Background: "背景資源",
  "Background blur offset": "背景模糊偏移",
  "Background blur": "背景模糊",
  "Battery level": "電量",
  "Blur intensity": "模糊強度",
  "Body angle": "身體角度",
  "Camera distance": "鏡頭距離",
  "Canvas layers": "畫布圖層",
  "Character (optional)": "角色（可選）",
  "Character voice": "角色語音",
  "Character model": "角色模型",
  "Chat preset": "聊天預設",
  "Choice ID": "選項識別",
  "Choice text": "選項文字",
  Color: "顏色",
  "Continue immediately": "連續執行",
  "Conversation thread": "對話串",
  "Costume index": "服裝序號",
  "Crossfade duration": "過渡時長",
  "Depth offset": "縱深偏移",
  "Destination label": "目標標籤",
  Dialogue: "對話內容",
  "Disable lip sync": "停用口型同步",
  "Displayed sender": "顯示發送者",
  "Displayed speaker name": "顯示角色名",
  "Displayed title": "顯示標題",
  Distance: "移動距離",
  Duration: "持續時間",
  Easing: "緩動",
  "Effect instance": "特效實例",
  "Environment component": "環境元件",
  "Face angle": "臉部角度",
  "Fade duration": "淡化時長",
  "Fade in": "淡入時長",
  "Fade out": "淡出時長",
  "Focus slide rate": "焦點滑動比例",
  Frame: "畫面框資源",
  "Frame instance": "畫面框實例",
  "Horizontal gaze": "水平注視",
  "Horizontal offset": "水平偏移",
  "Horizontal rotation": "水平旋轉",
  "Image opacity": "圖像透明度",
  "Light color / state": "輪廓光顏色 / 狀態",
  "Lip-sync character": "口型同步角色",
  "Lip-sync mode": "口型同步模式",
  "Live2D model": "Live2D 模型",
  Location: "地點",
  Message: "訊息內容",
  Motion: "動作",
  "Mouth opening": "嘴型開合幅度",
  Music: "音樂資源",
  "Name display": "名稱顯示",
  "Opacity transition": "透明度過渡時長",
  "Overlay opacity": "遮罩透明度",
  "World destination": "世界座標目標",
  "World position": "世界座標",
  Participants: "參與角色",
  "Playback delay": "播放延時",
  "Post effect": "後處理資源",
  "Preset index": "預設序號",
  "Queued start delay": "排隊播放延時",
  "Read count": "已讀數量",
  "Read target chat preset": "已讀目標",
  "Roll angle": "鏡頭滾轉角度",
  "Scene label": "場景標籤",
  "Screen mode": "螢幕模式",
  Sender: "發送者",
  "Sender chat preset": "發送者預設",
  "Shadow intensity": "陰影強度",
  "Sound effect": "音效資源",
  "Source character": "發起角色",
  "Stage position": "舞台站位",
  "Stamp asset": "貼圖資源",
  "Start delay": "開始延時",
  "Start offset": "播放起點",
  Still: "靜態畫面資源",
  "Stop fade": "停止淡出時長",
  "Stop mode": "停止方式",
  Strength: "強度",
  Subtitle: "字幕",
  "Target character position": "目標角色站位",
  "Target volume": "目標音量",
  "Timeline asset": "時間軸資源",
  "Transition duration": "轉場時長",
  "Transition mask": "轉場遮罩",
  "Typing text": "輸入狀態文字",
  "Vertical gaze": "垂直注視",
  "Vertical offset": "垂直偏移",
  "Vertical rotation": "垂直旋轉",
  Video: "影片資源",
  "Wait time": "等待時長",
  "Window style": "視窗樣式",
  "Zoom ratio": "縮放倍率",
};

const simplifiedChoiceLabels: Record<string, string> = {
  "Air lip sync": "气声口型同步",
  "Air lip sync · hold open": "气声口型同步（保持张口）",
  All: "全部",
  "All characters": "所有角色",
  "Anonymous (???)": "匿名（???）",
  Background: "背景",
  "Between 1 and 2": "站位 1 与 2 之间",
  "Between 2 and 3": "站位 2 与 3 之间",
  "Between 3 and 4": "站位 3 与 4 之间",
  "Between 4 and 5": "站位 4 与 5 之间",
  "Big close-up": "大特写",
  "Bust shot": "胸部镜头",
  Center: "中央",
  Character: "角色",
  "Character voice": "角色语音",
  Chat: "聊天",
  "Close-up": "近景",
  "Detail shot": "细节特写",
  Disabled: "关闭",
  Enabled: "开启",
  "Focus positions": "聚焦站位",
  Foreground: "前景",
  Frame: "画面框",
  Front: "最前层",
  "Hide name": "隐藏名称",
  Immediately: "立即停止",
  "Incoming call": "来电界面",
  "Knee shot": "膝上镜头",
  Lighting: "灯光",
  "Lock screen": "锁屏界面",
  Music: "音乐",
  Natural: "自然结束",
  None: "无",
  Normal: "正常",
  Overlay: "遮罩",
  Play: "播放",
  "Position 1": "站位 1",
  "Position 2": "站位 2",
  "Position 4": "站位 4",
  "Position 5": "站位 5",
  "Show name": "显示名称",
  "Sound effects": "音效",
  "Stage effects": "舞台特效",
  "Stage post effects": "舞台后处理",
  Start: "开始",
  Still: "静态画面",
  Stop: "停止",
  "Talk window": "对话框",
  "Up shot": "上半身镜头",
  Video: "视频",
  "Waist shot": "腰部镜头",
  Linear: "线性",
  "In sine": "正弦缓入",
  "Out sine": "正弦缓出",
  "In/out sine": "正弦缓入缓出",
  "In quad": "二次缓入",
  "Out quad": "二次缓出",
  "In/out quad": "二次缓入缓出",
  "In cubic": "三次缓入",
  "Out cubic": "三次缓出",
  "In/out cubic": "三次缓入缓出",
  "In quart": "四次缓入",
  "Out quart": "四次缓出",
  "In/out quart": "四次缓入缓出",
  "In quint": "五次缓入",
  "Out quint": "五次缓出",
  "In/out quint": "五次缓入缓出",
  "In expo": "指数缓入",
  "Out expo": "指数缓出",
  "In/out expo": "指数缓入缓出",
  "In circ": "圆形缓入",
  "Out circ": "圆形缓出",
  "In/out circ": "圆形缓入缓出",
  "In back": "回退缓入",
  "Out back": "回退缓出",
  "In/out back": "回退缓入缓出",
  "In bounce": "弹跳缓入",
  "Out bounce": "弹跳缓出",
  "In/out bounce": "弹跳缓入缓出",
};

const traditionalChoiceLabels: Record<string, string> = {
  ...simplifiedChoiceLabels,
  "Air lip sync": "氣聲口型同步",
  "Air lip sync · hold open": "氣聲口型同步（保持張口）",
  "All characters": "所有角色",
  "Anonymous (???)": "匿名（???）",
  Background: "背景",
  "Between 1 and 2": "站位 1 與 2 之間",
  "Between 2 and 3": "站位 2 與 3 之間",
  "Between 3 and 4": "站位 3 與 4 之間",
  "Between 4 and 5": "站位 4 與 5 之間",
  "Big close-up": "大特寫",
  "Bust shot": "胸部鏡頭",
  Character: "角色",
  "Character voice": "角色語音",
  Chat: "聊天",
  "Close-up": "近景",
  "Detail shot": "細節特寫",
  Disabled: "關閉",
  Enabled: "開啟",
  "Focus positions": "聚焦站位",
  Foreground: "前景",
  Frame: "畫面框",
  Front: "最前層",
  "Hide name": "隱藏名稱",
  Immediately: "立即停止",
  "Incoming call": "來電介面",
  "Knee shot": "膝上鏡頭",
  Lighting: "燈光",
  "Lock screen": "鎖定畫面",
  Music: "音樂",
  Natural: "自然結束",
  None: "無",
  Overlay: "遮罩",
  Play: "播放",
  "Show name": "顯示名稱",
  "Sound effects": "音效",
  "Stage effects": "舞台特效",
  "Stage post effects": "舞台後處理",
  Start: "開始",
  Still: "靜態畫面",
  "Talk window": "對話框",
  "Up shot": "上半身鏡頭",
  Video: "影片",
  "Waist shot": "腰部鏡頭",
  Linear: "線性",
  "In sine": "正弦緩入",
  "Out sine": "正弦緩出",
  "In/out sine": "正弦緩入緩出",
  "In quad": "二次緩入",
  "Out quad": "二次緩出",
  "In/out quad": "二次緩入緩出",
  "In cubic": "三次緩入",
  "Out cubic": "三次緩出",
  "In/out cubic": "三次緩入緩出",
  "In quart": "四次緩入",
  "Out quart": "四次緩出",
  "In/out quart": "四次緩入緩出",
  "In quint": "五次緩入",
  "Out quint": "五次緩出",
  "In/out quint": "五次緩入緩出",
  "In expo": "指數緩入",
  "Out expo": "指數緩出",
  "In/out expo": "指數緩入緩出",
  "In circ": "圓形緩入",
  "Out circ": "圓形緩出",
  "In/out circ": "圓形緩入緩出",
  "In back": "回退緩入",
  "Out back": "回退緩出",
  "In/out back": "回退緩入緩出",
  "In bounce": "彈跳緩入",
  "Out bounce": "彈跳緩出",
  "In/out bounce": "彈跳緩入緩出",
};

const japaneseFieldLabels: Record<string, string> = {
  "Overlay text": "バナーテキスト",
  "Stage position": "ステージ位置",
};

const koreanFieldLabels: Record<string, string> = {
  "Overlay text": "배너 텍스트",
  "Stage position": "스테이지 위치",
};

export const useStoryEditorLabels = () => {
  const { locale } = useLocale();

  const commandLabel = (name: AdvCommandName, fallback: string) => {
    if (locale.value === "zh-CN") return simplifiedCommandLabels[name];
    if (locale.value === "zh-TW") return traditionalCommandLabels[name];
    if (locale.value === "ja") return japaneseCommandLabels[name] || fallback;
    if (locale.value === "ko") return koreanCommandLabels[name] || fallback;
    return fallback;
  };

  const fieldLabel = (field: CommandFieldDescriptor) => {
    if (locale.value === "zh-CN") return simplifiedFieldLabels[field.label] || field.label;
    if (locale.value === "zh-TW") return traditionalFieldLabels[field.label] || field.label;
    if (locale.value === "ja") return japaneseFieldLabels[field.label] || field.label;
    if (locale.value === "ko") return koreanFieldLabels[field.label] || field.label;
    return field.label;
  };

  const choiceLabel = (label: string) => {
    if (locale.value === "zh-CN") return simplifiedChoiceLabels[label] || label;
    if (locale.value === "zh-TW") return traditionalChoiceLabels[label] || label;
    return label;
  };

  return { commandLabel, fieldLabel, choiceLabel };
};
