import type { TeamBuilderData } from "../../src/lib/team-builder/data";
// Entirely synthetic catalogue and account; no game files or private fixtures.
export const data: TeamBuilderData = {
  schema: "haneoka-team-builder-data-v1",
  identity: { server: "intl", releaseId: "r-" + "a".repeat(20), sourceId: "synthetic" },
  members: Object.fromEntries(
    Array.from({ length: 6 }, (_, i) => [
      i + 1,
      {
        id: i + 1,
        characterId: i + 1,
        bandId: 1,
        rarity: 4,
        attribute: 1,
        musicType: 1,
        name: `Synthetic ${i + 1}`,
        image: "",
        statMax: { performance: 100, technique: 100, visual: 100 },
        levelGroup: 1,
        trainingGroup: 1,
        awakeningGroup: 1,
        liveSkillId: 1,
        gekisoSkillId: 1,
        leaderSkillId: 0,
        bestMusicTagIds: [],
        trainingResourceGroup: 0,
        liveResourceGroup: 0,
        gekisoResourceGroup: 0,
        rankUpItemId: 0,
      },
    ]),
  ),
  snapshots: {
    "1": {
      id: 1,
      characterIds: [1],
      rarity: 4,
      attribute: 1,
      name: "Synthetic photo",
      image: "",
      statMax: { performance: 10, technique: 10, visual: 10 },
      levelGroup: 1,
      awakeningGroup: 1,
      supportSkillIds: [0, 0],
      gekisoSupportSkillIds: [0, 0],
    },
  },
  characters: Object.fromEntries(Array.from({ length: 6 }, (_, i) => [i + 1, { characterId: i + 1, bandId: 1 }])),
  bands: { "1": { id: 1 } },
  bandItems: { "1": { bandItemId: 1, bandId: 1, levels: [{ level: 1 }] } },
  songs: {},
  events: {},
  eventRules: {},
  progression: {
    memberCardLevels: [1, 2, 3].map((level) => ({
      group: 1,
      level,
      exp: String((level - 1) * 10),
      performanceRate: 10000,
      technicRate: 10000,
      visualRate: 10000,
    })),
    memberCardAwake: [1, 2].map((awakeCount) => ({ group: 1, awakeCount })),
    memberCardRanks: [1, 2].map((rank) => ({ group: 1, rank, leaderSkillLevel: 1 })),
    memberCardLevelLimits: [
      { rarity: 4, awakeCount: 1, limitLevel: 2 },
      { rarity: 4, awakeCount: 2, limitLevel: 3 },
    ],
    supportCardLevels: [1, 2, 3].map((level) => ({ group: 1, level, exp: String((level - 1) * 10) })),
    supportCardRanks: [{ group: 1, rank: 1, limitLevel: 3 }],
    characterRanks: [
      { rank: 1, exp: "0", value: 0 },
      { rank: 2, exp: "10", value: 1 },
    ],
    characterTotalRanks: [{ totalRank: 0, value: 0 }],
  },
  skills: {
    live: { "1": { effects: [{ level: 1 }, { level: 2 }] } },
    gekiso: { "1": { effects: [{ level: 1 }, { level: 2 }] } },
  },
  skillReference: {},
  liveTools: {},
  gekisoRules: {},
  gaps: [],
};
