import type { ThreeStoryScene } from "./three/ThreeStoryScene";

/**
 * Stable command-to-renderer port. Keeping this list explicit prevents the
 * story scheduler from reaching into Three/Cubism implementation details.
 */
export type StorySceneBackend = Pick<
  ThreeStoryScene,
  | "applyStageEnv"
  | "applyStageLight"
  | "applyStagePostEffect"
  | "cameraState"
  | "changeStageParticleEffects"
  | "captureStage"
  | "characterAtPosition"
  | "hasCharacterController"
  | "characterMotionIdentity"
  | "characterItems"
  | "clearCommandPostEffects"
  | "clearFrameOverlay"
  | "clearStill"
  | "cancelPendingCharacterDoF"
  | "closestFocusDataByZoomRatio"
  | "createSeekSnapshot"
  | "currentFocusData"
  | "destroy"
  | "fadeCharacter"
  | "fadeStill"
  | "fadeStageCapture"
  | "fadeVideo"
  | "flashWhite"
  | "focus"
  | "focusBaseCameraPosition"
  | "focusPoint"
  | "hideVideo"
  | "isCommandEffectPlaying"
  | "isCameraShakePlaying"
  | "isCharacterShowing"
  | "loadTexture"
  | "moveCharacter"
  | "moveCharacterToWorld"
  | "panFocusDistance"
  | "panV2"
  | "panV2CameraOffset"
  | "placeCharacter"
  | "playCommandEffect"
  | "playExpressionForTarget"
  | "playMotionForTarget"
  | "prepareCharacterAngle"
  | "prepareLook"
  | "prepareLookTarget"
  | "preloadLive2D"
  | "preloadTexture"
  | "removeCharacter"
  | "restoreSeekSnapshot"
  | "resetStageCapture"
  | "runRuleTransition"
  | "runStillCommand"
  | "settleSeekSnapshotResources"
  | "seekVideoRatio"
  | "seekSnapshotSafety"
  | "selectCharacterAssetIndex"
  | "setBackground"
  | "setBackgroundDoF"
  | "setBrightness"
  | "setRendererCharacterBrightness"
  | "setBackgroundBrightness"
  | "setCameraRoll"
  | "setCharacterAngle"
  | "setCharacterBack"
  | "setCharacterDoF"
  | "setCharacterForward"
  | "setCharacterPaused"
  | "setCharacterStagesY"
  | "setCommandPostEffect"
  | "setCover"
  | "setFrameOpacity"
  | "setFrameOverlay"
  | "setLook"
  | "setLookTarget"
  | "setPanV2BaseCameraPosition"
  | "setPanV2CameraOffset"
  | "setPlaybackSpeed"
  | "setPositionBrightness"
  | "setRimLight"
  | "setStill"
  | "setTilt"
  | "setup"
  | "disableCameraShake"
  | "enableCameraShake"
  | "shakeCommand"
  | "showVideo"
  | "showingCharacterTargets"
  | "skipVideo"
  | "sortCharacters"
  | "stagePoint"
  | "startTimedPseudoLipSync"
  | "startTimedHoldOpenPseudoLipSync"
  | "startTimedPseudoLipSyncSeconds"
  | "startVoiceLipSync"
  | "stopAllSpeaking"
  | "stopSpeaking"
  | "stopAllTimedPseudoLipSync"
  | "stopCommandEffects"
  | "stopTimedPseudoLipSync"
  | "waitVideoEnded"
  | "zoomByRatio"
>;

export type StoryResourceBackend = Pick<StorySceneBackend, "loadTexture" | "preloadTexture">;
