import type { Locale } from "../i18n/locales";
import type { ReleaseServer } from "../lib/release-server";

/**
 * The label table every catalogue screen is configured with.
 *
 * It lived inline in pages/[...slug].astro, which meant any other route that
 * wanted the same presentation — the community's Bestdori mirrors — had to
 * copy a hundred keys and then drift. One table, imported where needed.
 */
/** Client label names and their central catalog lookup aliases. */
export const LABEL_ENTRIES: ReadonlyArray<readonly [string, string]> = [
  ["filter", "common.actions.filter"],
  ["reset", "common.actions.reset"],
  ["search", "common.actions.search"],
  ["sort", "common.actions.sort"],
  ["id", "common.fields.id"],
  ["title", "common.fields.title"],
  ["release", "catalog.fields.release"],
  ["availability", "catalog.systems.common.availability"],
  ["order", "common.layout.order"],
  ["ascending", "common.layout.ascending"],
  ["descending", "common.layout.descending"],
  ["view", "common.actions.view"],
  ["downloadChart", "common.actions.downloadChart"],
  ["grid", "common.layout.grid"],
  ["list", "common.layout.list"],
  ["loading", "common.states.loading"],
  ["unavailable", "common.states.unavailable"],
  ["retry", "common.actions.retry"],
  ["empty", "common.states.empty"],
  ["close", "common.actions.close"],
  ["character", "catalog.fields.character"],
  ["band", "catalog.fields.band"],
  ["rarity", "catalog.cards.fields.rarity"],
  ["type", "catalog.fields.type"],
  ["attribute", "catalog.fields.attribute"],
  ["genre", "catalog.songs.fields.genre"],
  ["subtitle", "common.fields.subtitle"],
  ["category", "common.fields.category"],
  ["initial", "catalog.cards.types.permanent"],
  ["rankUpItem", "catalog.cards.fields.rankUpItem"],
  ["notes", "editors.chart.labels.notes"],
  ["battle", "navigation.battle"],
  ["performance", "catalog.cards.fields.performance"],
  ["technique", "catalog.cards.fields.technique"],
  ["visual", "catalog.cards.fields.visual"],
  ["composer", "catalog.songs.fields.composer"],
  ["lyricist", "catalog.songs.fields.lyricist"],
  ["arranger", "catalog.songs.fields.arranger"],
  ["birthday", "catalog.characters.fields.birthday"],
  ["height", "catalog.characters.fields.height"],
  ["voiceActor", "navigation.voiceActor"],
  ["school", "catalog.characters.fields.school"],
  ["hobby", "catalog.characters.fields.hobby"],
  ["value", "common.fields.value"],
  ["red", "catalog.songs.liveTypes.red"],
  ["blue", "catalog.songs.liveTypes.blue"],
  ["green", "catalog.songs.liveTypes.green"],
  ["yellow", "catalog.songs.liveTypes.yellow"],
  ["purple", "catalog.songs.liveTypes.purple"],
  ["original", "catalog.songs.types.original"],
  ["virtual", "catalog.songs.types.virtual"],
  ["jpop", "catalog.songs.types.jpop"],
  ["anime", "catalog.songs.types.anime"],
  ["game", "catalog.songs.types.game"],
  ["skills", "catalog.cards.fields.skills"],
  ["stats", "catalog.fields.stats"],
  ["details", "common.actions.details"],
  ["difficulty", "catalog.songs.fields.difficulty"],
  ["metaR", "catalog.analysis.fields.metaR"],
  ["metaTime", "catalog.analysis.fields.metaTime"],
  ["metaScore", "catalog.analysis.fields.metaScore"],
  ["metaNativeScore", "catalog.analysis.fields.metaNativeScore"],
  ["metaScoreFactor", "catalog.analysis.fields.metaScoreFactor"],
  ["metaEff", "catalog.analysis.fields.metaEff"],
  ["metaBpm", "catalog.analysis.fields.metaBpm"],
  ["metaN", "catalog.analysis.fields.metaN"],
  ["metaNps", "catalog.analysis.fields.metaNps"],
  ["metaSr", "catalog.analysis.fields.metaSr"],
  ["combo", "editors.chart.labels.combo"],
  ["metaMode", "catalog.analysis.fields.metaMode"],
  ["metaModeLive", "catalog.analysis.fields.metaModeLive"],
  ["metaModeGekisou", "catalog.analysis.fields.metaModeGekisou"],
  ["metaTierTheory", "catalog.analysis.fields.metaTierTheory"],
  ["metaTierCurrent", "catalog.analysis.fields.metaTierCurrent"],
  ["justableRate", "catalog.analysis.fields.justableRate"],
  ["justable", "catalog.analysis.fields.justable"],
  ["luck", "catalog.analysis.fields.luck"],
  ["metaEffCurrent", "catalog.analysis.fields.metaEffCurrent"],
  ["metaTier", "catalog.analysis.fields.metaTier"],
  ["metaTierTheorySub", "catalog.analysis.fields.metaTierTheorySub"],
  ["metaTierCurrentSub", "catalog.analysis.fields.metaTierCurrentSub"],
  ["gekisouSegment", "catalog.analysis.fields.gekisouSegment"],
  ["gekisouJustable", "catalog.analysis.fields.gekisouJustable"],
  ["gekisouMissionCombo", "catalog.songs.gekisou.gekisouMissionCombo"],
  ["gekisouMissionLuck", "catalog.songs.gekisou.gekisouMissionLuck"],
  ["gekisouMissionJustCount", "catalog.songs.gekisou.gekisouMissionJustCount"],
  ["gekisouMissionAll", "catalog.songs.gekisou.gekisouMissionAll"],
  ["gekisouMissionNone", "catalog.songs.gekisou.gekisouMissionNone"],
  ["gekisouPhase1", "catalog.analysis.fields.gekisouPhase1"],
  ["gekisouPhase2", "catalog.analysis.fields.gekisouPhase2"],
  ["gekisouPhase3", "catalog.analysis.fields.gekisouPhase3"],
  ["diary", "catalog.characters.fields.diary"],
  ["rewards", "catalog.fields.rewards"],
  ["content", "common.fields.content"],
  ["level", "common.fields.level"],
  ["maximum", "common.fields.maximum"],
  ["training", "catalog.cards.fields.training"],
  ["awakening", "catalog.cards.fields.awakening"],
  ["liveSkill", "catalog.cards.fields.liveSkill"],
  ["gekisouSkill", "catalog.cards.fields.gekisouSkill"],
  ["leaderSkill", "catalog.cards.fields.leaderSkill"],
  ["supportSkill", "catalog.cards.fields.supportSkill"],
  ["gekisouSupportSkill", "catalog.cards.fields.gekisouSupportSkill"],
  ["rank", "catalog.cards.fields.rank"],
  ["required", "common.fields.required"],
  ["memberPiece", "catalog.cards.fields.memberPiece"],
  ["total", "common.fields.total"],
  ["exp", "catalog.cards.fields.exp"],
  ["stage", "media.models.labels.stage"],
  ["memberCards", "navigation.memberCards"],
  ["supportCards", "navigation.supportCards"],
  ["songs", "navigation.songs"],
  ["characters", "navigation.characters"],
  ["lyrics", "catalog.songs.fields.lyrics"],
  ["arrangement", "catalog.songs.fields.arrangement"],
  ["size", "common.layout.size"],
  ["musicType", "catalog.songs.fields.musicType"],
  ["time", "common.fields.time"],
  ["score", "catalog.analysis.fields.score"],
  ["eff", "catalog.analysis.fields.eff"],
  ["bpm", "catalog.analysis.fields.bpm"],
  ["n", "catalog.analysis.fields.n"],
  ["nps", "catalog.analysis.fields.nps"],
  ["sr", "catalog.analysis.fields.sr"],
  ["play", "common.actions.play"],
  ["pause", "common.actions.pause"],
  ["chart", "navigation.chart"],
  ["media", "navigation.media"],
  ["mv", "catalog.songs.fields.mv"],
  ["playAll", "media.audio.playAll"],
  ["previous", "common.actions.previous"],
  ["next", "common.actions.next"],
  ["friendship", "catalog.characters.fields.friendship"],
  ["effectsByLevel", "catalog.cards.fields.effectsByLevel"],
  ["profile", "catalog.characters.fields.profile"],
  ["cards", "navigation.cards"],
  ["stamps", "navigation.stamps"],
  ["voices", "navigation.voices"],
  ["story", "navigation.story"],
  ["characterBonds", "catalog.characters.fields.characterBonds"],
  ["bandStories", "story.navigation.band"],
  ["linkStories", "story.navigation.link"],
  ["homeStories", "story.navigation.home"],
  ["afterliveStories", "story.navigation.afterlive"],
  ["tutorialStories", "story.navigation.tutorial"],
  ["schoolClass", "catalog.characters.fields.schoolClass"],
  ["constellation", "catalog.characters.fields.constellation"],
  ["favoriteFood", "catalog.characters.fields.favoriteFood"],
  ["hatedFood", "catalog.characters.fields.hatedFood"],
  ["missions", "navigation.missions"],
  ["simple", "common.layout.simple"],
  ["watch", "common.actions.watch"],
  ["density", "common.layout.density"],
  ["comfortable", "common.layout.comfortable"],
  ["compact", "common.layout.compact"],
  ["remove", "common.actions.remove"],
  // Rotating game systems (events, gacha, shop, …) share the system.* copy.
  ["status", "catalog.systems.common.status"],
  ["price", "catalog.shop.price"],
  ["ongoing", "catalog.systems.common.ongoing"],
  ["upcoming", "catalog.systems.common.upcoming"],
  ["ended", "catalog.systems.common.ended"],
  ["retired", "catalog.systems.common.retired"],
  ["starts", "catalog.systems.common.starts"],
  ["ends", "catalog.systems.common.ends"],
  ["MemberCard", "catalog.resources.types.MemberCard"],
  ["SupportCard", "catalog.resources.types.SupportCard"],
  ["Item", "catalog.resources.types.Item"],
  ["stars", "catalog.recruitments.types.stars"],
  ["ticket", "catalog.recruitments.types.ticket"],
  ["ad", "catalog.recruitments.types.ad"],
  ["pass", "catalog.recruitments.types.pass"],
  ["featured", "catalog.systems.common.featured"],
  ["drawOptions", "catalog.recruitments.drawOptions"],
  ["draw", "catalog.recruitments.draw"],
  ["drawOne", "catalog.recruitments.drawOne"],
  ["drawCount", "catalog.recruitments.drawCount"],
  ["rates", "catalog.recruitments.rates"],
  ["simulator", "catalog.recruitments.simulator"],
  ["simulatorNote", "catalog.recruitments.simulatorNote"],
  ["simulateDraw", "catalog.recruitments.simulateDraw"],
  ["nextDrawCost", "catalog.recruitments.nextDrawCost"],
  ["remainingDrawUses", "catalog.recruitments.remainingDrawUses"],
  ["guaranteedDraws", "catalog.recruitments.guaranteedDraws"],
  ["resetSimulator", "catalog.recruitments.resetSimulator"],
  ["simulationUnavailable", "catalog.recruitments.simulationUnavailable"],
  ["simulationLimitReached", "catalog.recruitments.simulationLimitReached"],
  ["simulationComplete", "catalog.recruitments.simulationComplete"],
  ["latestDrawResults", "catalog.recruitments.latestDrawResults"],
  ["spent", "catalog.recruitments.spent"],
  ["gachaPoint", "catalog.recruitments.gachaPoint"],
  ["guaranteed", "catalog.recruitments.guaranteed"],
  ["pickup", "catalog.recruitments.pickup"],
  ["firstTime", "catalog.shop.firstTime"],
  ["bonus", "catalog.systems.common.bonus"],
  ["prizePool", "catalog.recruitments.prizePool"],
  ["dailyRewards", "catalog.passes.dailyRewards"],
  ["dayN", "catalog.passes.day"],
  ["contents", "catalog.systems.common.contents"],
  ["eventRewards", "catalog.events.labels.eventRewards"],
  ["achievementRewards", "catalog.events.labels.achievementRewards"],
  ["boxGachaRewards", "catalog.events.labels.boxGachaRewards"],
  ["rankingRewards", "catalog.events.labels.rankingRewards"],
  ["liveEventRewards", "catalog.events.labels.liveEventRewards"],
  ["challengeRewards", "catalog.events.labels.challengeRewards"],
  ["loopRewards", "catalog.events.labels.loopRewards"],
  ["rewardUnavailable", "catalog.events.labels.rewardUnavailable"],
  ["eventWindow", "catalog.events.labels.eventWindow"],
  ["displayEnd", "catalog.events.labels.displayEnd"],
  ["eventRankings", "catalog.events.labels.eventRankings"],
  ["liveRanking", "catalog.events.labels.liveRanking"],
  ["challengeRanking", "catalog.events.labels.challengeRanking"],
  ["loopStart", "catalog.events.labels.loopStart"],
  ["eventDetailsUnavailable", "catalog.events.labels.eventDetailsUnavailable"],
  ["eventEffects", "catalog.events.labels.eventEffects"],
  ["eventEffect", "catalog.events.labels.eventEffect"],
  ["eventLinks", "catalog.events.labels.eventLinks"],
  ["eventItem", "catalog.events.labels.eventItem"],
  ["eventSong", "catalog.events.labels.eventSong"],
  ["storyEpisode", "catalog.events.labels.storyEpisode"],
  ["goal", "catalog.events.labels.goal"],
  ["eventMainStory", "story.navigation.event"],
  ["eventExtraStory", "story.labels.extraStory"],
  ["eventAnotherStory", "story.labels.anotherStory"],
  ["exchangeGoods", "catalog.exchange.exchangeGoods"],
  ["rankRewards", "catalog.systems.common.rankRewards"],
  ["levelRewards", "catalog.systems.common.levelRewards"],
  ["passMissions", "catalog.passes.passMissions"],
  ["points", "catalog.systems.common.points"],
  ["premium", "catalog.passes.premium"],
  ["free", "catalog.passes.free"],
  ["limit", "catalog.shop.limit"],
  ["viewSong", "catalog.systems.common.viewSong"],
  ["watchAd", "catalog.passes.watchAd"],
  ["inAppPurchase", "catalog.shop.inAppPurchase"],
  ["requiresRank", "catalog.systems.common.requiresRank"],
  ["bands", "catalog.fields.band"],
  ["game-event", "catalog.events.kind.gameEvent"],
  ["real-live", "catalog.events.kind.realLive"],
  ["gacha", "navigation.gacha"],
  ["login", "navigation.loginCampaigns"],
  ["shop", "navigation.shop"],
  ["exchange", "navigation.exchange"],
  ["circle", "navigation.circle"],
  ["challenge", "navigation.challenge"],
  ["regular-mission", "catalog.missions.regularMission"],
  ["limited-mission", "catalog.missions.limitedMission"],
  ["season-pass", "catalog.passes.seasonPass"],
  ["monthly-pass", "catalog.passes.monthlyPass"],
];
const LABEL_ALIASES: Readonly<Record<string, string>> = Object.freeze(Object.fromEntries(LABEL_ENTRIES));
/** Resolve a catalogue controller field ID to its declared message path. */
export const catalogLabelPath = (key: string): string | undefined =>
  Object.hasOwn(LABEL_ALIASES, key) ? LABEL_ALIASES[key] : undefined;

export interface CatalogConfigOptions {
  resource: string;
  locale: Locale;
  server?: ReleaseServer;
  entityKind?: string;
  entityId?: string;
  entityContext?: boolean;
  /** Render a canonical song's chart as its own child page. */
  chartPage?: boolean;
  aspectRatio?: string;
  origin?: "release" | "bestdori";
  nativeMetaReference?: unknown;
}

/** Serialises a catalogue screen's configuration. */
export function catalogConfig(options: CatalogConfigOptions): string {
  return JSON.stringify({
    resource: options.resource,
    locale: options.locale,
    ...(options.server ? { server: options.server } : {}),
    ...(options.entityKind ? { entityKind: options.entityKind } : {}),
    ...(options.entityId ? { entityId: options.entityId } : {}),
    ...(options.entityContext ? { entityContext: true } : {}),
    ...(options.chartPage ? { chartPage: true } : {}),
    labelAliases: LABEL_ALIASES,
    aspectRatio: options.aspectRatio ?? "1",
    ...(options.origin ? { origin: options.origin } : {}),
    ...(options.nativeMetaReference ? { nativeMetaReference: options.nativeMetaReference } : {}),
  });
}
